<!DOCTYPE html>
<html lang="fr" class="wide wow-animation">
  <head>
    <!--Site Title-->
    <title>Bornes connectées | Paparazza</title>
    <meta charset="utf-8">
    <meta name="description" content="Location / Vente de bornes connectées, boostez vos évènements avec nos bornes photos, bornes hashtag, jukebox, digisport 2.0, livre d'or numérique">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <!--Stylesheets-->
    <link rel="icon" href="<?= url('ressources/images/logo-small.png')?>" type="image/x-icon">

    <!--Bootstrap-->
    <link rel="stylesheet" href="<?= url('ressources/css/style.css')?>">
    <link rel="stylesheet" href="<?= url('ressources/css/overwriting.css')?>">
<!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/.."><img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script><![endif]-->
  </head>

  <body>
    <!--The Main Wrapper-->
    <div class="page">
      <!--
      ========================================================
                              HEADER
      ========================================================
      -->
      <header class="page-header">

        <!--RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar bg-white top-panel-none-items" data-lg-device-layout="rd-navbar-static" data-layout="rd-navbar-fixed" data-hover-on="false" data-stick-up="false" data-sm-layout="rd-navbar-fullwidth">
            <div class="rd-navbar-inner">

              <!--RD Navbar Panel-->
              <div class="rd-navbar-panel">

                <!--RD Navbar Toggle-->
                <button data-rd-navbar-toggle=".rd-navbar" class="rd-navbar-toggle"><span></span></button>
                <!--END RD Navbar Toggle-->

                <!--RD Navbar Brand-->
                <div class="rd-navbar-brand"><a href="#" class="brand-name">
                    <img id="logo-small" src="<?= url('ressources/images/logo-small.png')?>" style="text-center" alt="">
                    <img id="logo-text" src="<?= url('ressources/images/logo-txt.png')?>" style="text-center" alt="">
                </a></div>
                <!--END RD Navbar Brand-->
              </div>
              <!--END RD Navbar Panel-->

              <div class="rd-navbar-nav-wrap">


                <!--RD Navbar Nav-->
                <ul class="rd-navbar-nav">
                  <li><a href="#">Accueil</a></li>
                  <li><a href="#products">Nos Produits</a>
                    <ul class="rd-navbar-dropdown">
                        <li><a href="#hashtag">Borne hashtag</a></li>
                        <li><a href="#photo">Selfy Station</a></li>
                        <li><a href="#livre-or">Livre d'or</a></li>
                        <li><a href="#digisport">Digisport 2.0</a></li>
                    </ul>
                  </li>
                  <li><a href="#prestations">Nos Prestations</a></li>
                  <li><a href="#gallery">Galerie Photo</a></li>
                  <li><a href="#contact">Contact</a></li>
                  <li><a href="#selling">Vente</a></li>
                  <?php if (isLogged()): ?>
                      <li><a href="#"><i class="fa fa-caret-square-o-down" aria-hidden="true"></i></a>
                          <ul class="rd-navbar-dropdown">
                              <li><a href="<?= url('admin/dashboard') ?>">Tableau de bord</a></li>
                              <li><a href="<?= url('logout') ?>">Déconnexion</a></li>
                          </ul>
                      </li>
                  <?php endif; ?>
                </ul>
                <!--END RD Navbar Nav-->
              </div>
            </div>
          </nav>
        </div>
        <!--END RD Navbar-->

        <!--SLIDER-->
        <?php include('pages/slider.phtml') ?>

      </header>
      <!--
      ========================================================
                              CONTENT
      ========================================================
      -->
      <main class="page-content undefined">


        <!-- Start section -->

        <!-- Mosaique produits -->
        <?php include('pages/products-mosaique.phtml'); ?>


        <!-- Pastilles produits -->
        <?php include('pages/products-pastilles.phtml'); ?>


        <!--Products Section-->
        <?php include('pages/products.phtml'); ?>


        <!-- Prestations-->
        <?php include('pages/prestations.phtml'); ?>


        <!-- Galerie photo -->
        <?php include('pages/gallery.phtml'); ?>


        <!-- Partenaires -->
        <?php include('pages/partenaires.phtml'); ?>


        <!-- SELLING -->
        <?php include('pages/selling.phtml'); ?>


        <!-- Contact -->
        <?php include('pages/contact.phtml');  ?>


      </main>
      <!--
      ========================================================
                              FOOTER
      ========================================================
      -->

      <?php include('pages/footer.phtml'); ?>

    </div>
    <!--Core Scripts-->
    <script src="<?= url('ressources/js/core.min.js')?>"></script>
    <!--jQuery (necessary for Bootstrap's JavaScript plugins)-->
    <!--Include all compiled plugins (below), or include individual files as needed-->
    <script src="<?= url('ressources/js/bootstrap.min.js')?>"></script>
    <!--Additional Functionality Scripts-->
    <script src="<?= url('ressources/js/script.js')?>"></script>
    <script src="<?= url('ressources/js/overwriting.js')?>"></script>
  </body>
</html>
