<!DOCTYPE html>
<html lang="en" class="wide wow-animation">
  <head>
    <!--Site Title-->
    <title>Paparazza</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <!--Stylesheets-->
    <link rel="icon" href="<?= url('ressources/images/client_src/logo-small.png')?>" type="image/x-icon">

    <!--Bootstrap-->
    <link rel="stylesheet" href="<?= url('ressources/css/style.css')?>">
    <link rel="stylesheet" href="<?= url('ressources/css/overwriting.css')?>">
<!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/.."><img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script><![endif]-->
  </head>

  <body>
    <!--The Main Wrapper-->
    <div class="page">
      <!--
      ========================================================
                              HEADER
      ========================================================
      -->
      <header class="page-header">

        <!--RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar bg-white top-panel-none-items" data-lg-device-layout="rd-navbar-static" data-layout="rd-navbar-fixed" data-hover-on="false" data-stick-up="false" data-sm-layout="rd-navbar-fullwidth">
            <div class="rd-navbar-inner">

              <!--RD Navbar Panel-->
              <div class="rd-navbar-panel">

                <!--RD Navbar Toggle-->
                <button data-rd-navbar-toggle=".rd-navbar" class="rd-navbar-toggle"><span></span></button>
                <!--END RD Navbar Toggle-->

                <!--RD Navbar Brand-->
                <div class="rd-navbar-brand"><a href="#" class="brand-name">
                    <img id="logo-small" src="<?= url('ressources/images/logo-small.png')?>" style="text-center" alt="">
                    <img id="logo-text" src="<?= url('ressources/images/logo-txt.png')?>" style="text-center" alt="">
                </a></div>
                <!--END RD Navbar Brand-->
              </div>
              <!--END RD Navbar Panel-->

              <div class="rd-navbar-nav-wrap">


                <!--RD Navbar Nav-->
                <ul class="rd-navbar-nav">
                  <li><a href="#">Accueil</a></li>
                  <li><a href="#products">Nos Produits</a>
                    <ul class="rd-navbar-dropdown">
                        <li><a href="#hashtag">Borne hashtag</a></li>
                        <li><a href="#photo">Selfy Station</a></li>
                        <li><a href="#livre-or">Livre d'or</a></li>
                        <li><a href="#digisport">Digisport 2.0</a></li>
                    </ul>
                  </li>
                  <li><a href="#prestations">Nos Prestations</a></li>
                  <li><a href="#contact">Contact</a></li>
                  <li><a href="#selling">Vente</a></li>
                  <?php if (isLogged()): ?>
                      <li><a href="<?= url('logout') ?>">Déconnexion</a></li>
                  <?php endif; ?>
                </ul>
                <!--END RD Navbar Nav-->
              </div>
            </div>
          </nav>
        </div>
        <!--END RD Navbar-->
        <section>
          <!--Swiper-->
          <div data-autoplay="5000" data-slide-effect="fade" data-loop="false" data-height="36,45833333333333%" data-min-height="400px" class="swiper-container swiper-slider swiper-container-horizontal swiper-container-fade" style="height: 400px;">
            <div class="container container-wide slider-container">
              <div class="jumbotron text-center bg-btn">
                <h1 data-wow-duration="2s" class="wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">PAPARAZZA<small data-wow-duration="2s" class="wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">Boostez vos évènements</small></h1>
                <p data-wow-duration="2s" class="big wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;"></p>
              </div>
            </div>
            <div class="swiper-wrapper" style="transition-duration: 0ms;">
              <div data-slide-bg="<?= url('ressources/images/slider/2.jpg')?>" class="swiper-slide swiper-slide-prev" style="background-image: url(&quot;images/slide-1.jpg&quot;); background-size: cover; width: 791px; opacity: 1; transform: translate3d(0px, 0px, 0px); transition-duration: 0ms;">
                <div class="swiper-slide-caption"></div>
              </div>
              <div data-slide-bg="<?= url('ressources/images/slider/6.jpg')?>" class="swiper-slide swiper-slide-active" style="background-image: url(&quot;images/slide-2.jpg&quot;); background-size: cover; width: 791px; opacity: 1; transform: translate3d(-791px, 0px, 0px); transition-duration: 0ms;">
                <div class="swiper-slide-caption"></div>
              </div>
              <div data-slide-bg="<?= url('ressources/images/slider/3.jpg')?>" class="swiper-slide swiper-slide-next" style="background-image: url(&quot;images/slide-3.jpg&quot;); background-size: cover; width: 791px; opacity: 0; transform: translate3d(-1582px, 0px, 0px); transition-duration: 0ms;">
                <div class="swiper-slide-caption"></div>
              </div>
            </div>
            <!--Swiper Pagination-->
            <div class="swiper-pagination swiper-pagination-clickable"><span class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet swiper-pagination-bullet-active"></span><span class="swiper-pagination-bullet"></span></div>
          </div>
        </section>

      </header>
      <!--
      ========================================================
                              CONTENT
      ========================================================
      -->
      <main class="page-content undefined">


        <!-- Start section -->
        <section class="well well-sm page-sample">
          <div class="container container-wide">

            <h2 class="text-center">Boostez vos événements avec une borne connectée ou un jeu DIGI-SPORTS 2.0</h2>


              <!-- Mosaique produits -->
              <div class="mosaique row row-no-gutter offset-2">
                  <div class="col-xs-6 col-sm-6 col-md-3">
                    <div class="img-thumbnail text-center"><a href="#hashtag" class="mfp-image"><img src="<?= url('ressources/images/hashtag_jaune.png')?>" alt="hashtag_jaune" class="img-wide">
                        <div class="caption">
                          <h1>BORNE HASHTAG</h1>
                          <p>En savoir plus</p>
                        </div><span class="overlay"></span></a></div>
                  </div>
                  <div class="col-xs-6 col-sm-6 col-md-3">
                    <div class="img-thumbnail text-center"><a href="#photo" class="mfp-image"><img src="<?= url('ressources/images/photo_bleu.png')?>" alt="camera bleue" class="img-wide">
                        <div class="caption">
                          <h1>BORNE SELFY STATION</h1>
                          <p>En savoir plus</p>
                        </div><span class="overlay"></span></a></div>
                  </div>
                <div class="col-xs-6 col-sm-6 col-md-3">
                  <div class="img-thumbnail text-center"><a href="#livre-or" class="mfp-image"><img src="<?= url('ressources/images/livre_orange.png')?>" alt="livre orange" class="img-wide">
                      <div class="caption">
                        <h1>LIVRE D'OR NUMERIQUE</h1>
                        <p>En savoir plus</p>
                      </div><span class="overlay"></span></a></div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-3">
                  <div class="img-thumbnail text-center"><a href="#digisport" class="mfp-image"><img src="<?= url('ressources/images/sport_violet.png')?>" alt="ballon violet" class="img-wide">
                      <div class="caption">
                        <h1>DIGISPORT</h1>
                        <p>En savoir plus</p>
                      </div><span class="overlay"></span></a></div>
                </div>
              </div>
          </div>
        </section>


        <!-- pastilles -->
        <section class="well text-center">
            <h2 class="text-center">Rendez vos invités actifs en leur proposant une borne adaptée à votre événement :</h2>
            <hr>
          <div class="container container-wide  text-sm-left">
            <div class="row flow-offset-1">
              <div class="row clearfix">
                  <div class="col-sm-6 col-md-4 col-md-offset-2">
                    <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                      <div class="box__left"><span class="icon icon-lg icon-primary fa-hashtag"></span></div>
                      <div class="box__body">
                        <h4 class="text-bold inset-1"><a href="#hashtag">Borne Hashtag</a></h4>
                        <p class="small text-darker">Basée sur le selfie envoyé par Instagram et Twitter sur un hashtag réservé à votre événement, imprime les photos en format polaroid personnalisé.</p>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-4 col-md-offset-2">
                    <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                      <div class="box__left"><span class="icon icon-lg icon-primary fa-camera"></span></div>
                      <div class="box__body">
                        <h4 class="text-bold inset-1"><a href="#pĥoto">Borne Selfy Station</a></h4>
                        <p class="small text-darker">Véritable studio photo mobile, cette borne photographique imprime sous divers formats, partage par mail et réseaux sociaux.</p>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="row flow-offset-1">
                  <div class="col-sm-6 col-md-4">
                    <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                      <div class="box__left"><span class="icon icon-lg icon-primary fa-book"></span></div>
                      <div class="box__body">
                        <h4 class="text-bold inset-1"><a href="#livre-or">Livre d'or Numérique</a></h4>
                        <p class="small text-darker">Une tablette numérique qui passe de main en main pour faire une photo, une vidéo, écrire un message sur l'écran tactile.</p>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-4 col-md-offset-2">
                    <div data-wow-duration="2s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">
                      <div class="box__left"><span class="icon icon-lg icon-primary fa-futbol-o"></span></div>
                      <div class="box__body">
                        <h4 class="text-bold inset-1"><a href="#digisport">DigiSport 2.0</a></h4>
                        <p class="small text-darker">Attirez du public sur votre stand avec nos jeux sportif sur mur digital</p>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </section>



        <!--Products Section-->
        <?php include($template . '.phtml'); ?>

        <!-- Prestations-->

        <section id="prestations" class="well well-sm text-center">
          <h2 class="text-center inset-1">Nos Prestations</h2>

          <hr>
          <div class="container container-wide">
            <div class="row row-no-gutter">
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2> location borne photo</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>forfait 3 heures</li>
                    <li>forfait journée</li>
                    <li>forfait soirée</li>
                    <li>forfait week-end</li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2> location borne hashtag</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>forfait journée ou soirée</li>
                    <li>impression illimitée</li>
                    <li>1 ou 2 hashtags dédiés à l'événement</li>
                    <li>Envoi simultané dans un album de votre Facebook</li>
                    <li></li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2> location imprimante</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>Nos imprimantes thermiques peuvent être louées, devis sur demande.</li>
                    <li></li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2> vente de bornes</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>renseignement et prix sur demande</li>
                    <li></li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
            </div>
          </div>
        </section>

        <!-- Partenaires -->
        <section class="well well-sm text-center">
            <div class="container container-wide">
                <div class="text-center well-bottom">
                    <h2>Ils ont boosté leurs évènements</h2>
                    <hr>
                </div>
              <ul class="flex-list well-top text-center">
                  <!-- le template propose de faire une page clients, on garde ou pas ?? -->
                <li><a href="clients.html"><img src="<?= url('ressources/images/client-1.png')?>" alt="" class="client"></a></li>
                <li><a href="clients.html"><img src="<?= url('ressources/images/client-2.jpg')?>" alt="" class="client"></a></li>
                <li><a href="clients.html"><img src="<?= url('ressources/images/client-3.jpg')?>" alt="" class="client"></a></li>
                <li><a href="clients.html"><img src="<?= url('ressources/images/client-4.jpg')?>" alt="" class="client"></a></li>
              </ul>
            </div>
          </section>

          <!-- SELLING -->
        <section id="selling" class="text-center well bg-dark">
          <div class="container container-wide">
            <div class="col-xs-12 border-bottom well">
              <h2 class="text-center">Vente de Matériel</h2>
              <hr class="text-center">
              <div class="row">
                <div class="col-sm-5">
                  <!--Tabs-->
                  <ul id="myTabs2" role="tablist" class="nav nav-tabs vertical-tabs text-center">
                    <li role="presentation" class="active"><a href="#vtab0" aria-controls="vtab0" role="tab" class="fa-television">Borne Photo Type Caisse de Transport<span class="fa-chevron-right"></span></a></li>
                    <li role="presentation"><a href="#vtab1" aria-controls="vtab1" role="tab" class="fa-thumbs-up">Borne Photo<span class="fa-chevron-right"></span></a></li>
                  </ul>
                </div>
                <div class="col-sm-offset-1 col-sm-6">
                  <!--Tab panes-->
                  <div class="tab-content vertical-tabs text-sm-left">
                    <div role="tabpanel" id="vtab0" class="tab-pane active fade in blog-post">
                      <div class="bg-dark-blue-2">
                        <img src="<?= url('ressources/images/ct27.png')?>" alt="borne ct27" class="verticaly-centered bordered products">
                      </div>
                      <ul class="inset-2 text-darker caption bg-white article-column-text">NEUF - Réf CT27
                        <li>Structure 2 étages séparables type caisse de transport</li>
                        <li>Appareil photo Canon 700D </li>
                        <li>Imprimante DNP DS620 </li>
                        <li>Flash 180w</li>
                        <li>Pc tout en un Lenovo ou équivalent, écran tactile 21.5 pouces</li>
                      </ul>
                    </div>
                    <div role="tabpanel" id="vtab1" class="tab-pane fade blog-post">
                      <div class="bg-dark-blue-2">
                        <img src="<?= url('ressources/images/S2.jpg')?>" alt="borne S2" class="verticaly-centered bordered products">
                      </div>
                      <ul class="inset-2 text-darker caption bg-white article-column-text">OCCASION - Réf S2S2
                        <li>En parfait état de fonctionnement</li>
                        <li>Appareil photo Canon 700D</li>
                        <li>Imprimante Mitsubishi cp-d70dw</li>
                        <li>Flash wallimex pro</li>
                        <li>Pc tout en un Dell, écran tactile 18 pouces</li>
                        <li>Leds pour éclairage constant</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <!-- Contact -->
        <section id="contact" class="contact-form text-center text-sm-left well well-sm">
          <div class="container container-wide">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 text-center well-bottom">
                <h1>CONTACTEZ NOUS</h1>
                <hr>
                <p>Nos services vous intéressent ? Contactez-nous via le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.</p>
              </div>
              <div class="col-xs-12">
                <div class="row flow-offset-3">
                  <div class="col-md-3 col-md-offset-1 text-center text-md-left">
                    <div class="contact-info-2">
                      <h4>Addresse</h4>
                      <address class="small text-darker">Pôle Pixel, 26 rue Emile Decorps<br>Bâtiment Minoterie<br>Villeurbanne, 69100</address>
                      <h4>Téléphone</h4>
                      <address class="small text-darker"><a href="callto:#">06 70 53 48 90</a></address>
                      <h4>Email</h4>
                      <address class="small text-darker"><a href="mailto:#">contact@paparazza.fr</a></address>
                    </div>
                    <ul class="list-inline big text-dark">
                      <li><a href="https://www.instagram.com/paparazza_lyon" class="fa-instagram"></a></li>
                      <li><a href="#" class="fa-linkedin"></a></li>
                      <li><a href="https://fr-fr.facebook.com/bornesconnectees" class="fa-facebook"></a></li>
                    </ul>
                  </div>
                  <div class="col-md-7">
                    <form method="post" action="bat/rd-mailform.php" class="rd-mailform">
                      <!--RD Mailform Type-->
                      <input type="hidden" name="form-type" value="contact">
                      <!--END RD Mailform Type-->
                      <div class="form-group">
                        <label for="exampleInputText1"></label>
                        <input type="text" placeholder="Votre Nom" name="name" data-constraints="@NotEmpty @LettersOnly" id="exampleInputText1" class="form-control">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1"></label>
                        <input placeholder="Votre email" type="text" name="email" data-constraints="@NotEmpty @Email" id="exampleInputEmail1" class="form-control">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputText2"></label>
                        <input type="text" placeholder="Téléphone" name="tel" data-constraints="@NotEmpty " id="exampleInputText2" class="form-control">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputText3"></label>
                        <input type="text" placeholder="Date et type de l'évènement" name="date_type" data-constraints="@NotEmpty " id="exampleInputText3" class="form-control">
                      </div>
                      <div class="form-group textarea">
                        <label for="exampleTextarea"></label>
                        <textarea id="exampleTextarea" rows="3" placeholder="Votre message ici..." name="message" data-constraints="@NotEmpty" class="form-control"></textarea>
                      </div>
                      <button type="submit" class="btn btn-primary">Envoyer</button>
                      <div class="mfInfo"></div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>



      </main>
      <!--
      ========================================================
                              FOOTER
      ========================================================
      -->

      <footer class="page-footer footer-centered text-center bg-dark">
        <section class="footer-content">
          <div class="container container-wide">
            <div class="navbar-brand"><a href="index.html">PAPARAZZA</a></div>
            <address>Pôle Pixel<br>26 rue Emile Decorps<br>Villeurbanne, 69100</address>
            <address><a href="callto:#">06 70 53 48 90<br></a><a href="mailto:#">contact@paparazza.fr</a></address>
            <ul class="list-inline">
              <li><a href="https://www.instagram.com/paparazza_lyon" class="fa-instagram"></a></li>
              <li><a href="#" class="fa-linkedin"></a></li>
              <li><a href="https://fr-fr.facebook.com/bornesconnectees" class="fa-facebook"></a></li>
            </ul>
          </div>
        </section>
        <section class="rights">
          <p class="copyright">Paparazza<span id="copyright-year"></span> All Rights Reserved <a href="terms.html" class="text-primary">Terms of Use</a> | <a href="terms.html" class="text-primary">Privacy Policy</a></p>
        </section>
      </footer>

    </div>
    <!--Core Scripts-->
    <script src="<?= url('ressources/js/core.min.js')?>"></script>
    <!--jQuery (necessary for Bootstrap's JavaScript plugins)-->
    <!--Include all compiled plugins (below), or include individual files as needed-->
    <script src="<?= url('ressources/js/bootstrap.min.js')?>"></script>
    <!--Additional Functionality Scripts-->
    <script src="<?= url('ressources/js/script.js')?>"></script>
    <script src="<?= url('ressources/js/overwriting.js')?>"></script>
  </body>
</html>
