<!DOCTYPE html>
<html lang="fr" class="wide wow-animation">
  <head>
    <!--Site Title-->
    <title>Mentions légales | Paparazza</title>
    <meta charset="utf-8">
    <meta name="description" content="Location / Vente de bornes connectées, boostez vos évènements avec nos bornes photos, bornes hashtag, jukebox, digisport 2.0, livre d'or numérique">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <!--Stylesheets-->
    <link rel="icon" href="<?= url('ressources/images/logo-small.png')?>" type="image/x-icon">

    <!--Bootstrap-->
    <link rel="stylesheet" href="<?= url('ressources/css/style.css')?>">
    <link rel="stylesheet" href="<?= url('ressources/css/overwriting.css')?>">
<!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/.."><img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script><![endif]-->
  </head>

  <body>
    <!--The Main Wrapper-->
    <div class="page">
      <!--
      ========================================================
                              HEADER
      ========================================================
      -->
      <header class="page-header">

        <!--RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar bg-white top-panel-none-items" data-lg-device-layout="rd-navbar-static" data-layout="rd-navbar-fixed" data-hover-on="false" data-stick-up="false" data-sm-layout="rd-navbar-fullwidth">
            <div class="rd-navbar-inner">

              <!--RD Navbar Panel-->
              <div class="rd-navbar-panel">

                <!--RD Navbar Toggle-->
                <button data-rd-navbar-toggle=".rd-navbar" class="rd-navbar-toggle"><span></span></button>
                <!--END RD Navbar Toggle-->

                <!--RD Navbar Brand-->
                <div class="rd-navbar-brand"><a href="#" class="brand-name">
                    <img id="logo-small" src="<?= url('ressources/images/logo-small.png')?>" style="text-center" alt="">
                    <img id="logo-text" src="<?= url('ressources/images/logo-txt.png')?>" style="text-center" alt="">
                </a></div>
                <!--END RD Navbar Brand-->
              </div>
              <!--END RD Navbar Panel-->

              <div class="rd-navbar-nav-wrap">


                <!--RD Navbar Nav-->
                <ul class="rd-navbar-nav">
                  <li><a href="<?= url('home') ?>">Retour au site</a></li>
                  <?php if (isLogged()): ?>
                      <li><a href="#"><i class="fa fa-caret-square-o-down" aria-hidden="true"></i></a>
                          <ul class="rd-navbar-dropdown">
                              <li><a href="<?= url('admin/dashboard') ?>">Tableau de bord</a></li>
                              <li><a href="<?= url('logout') ?>">Déconnexion</a></li>
                          </ul>
                      </li>
                  <?php endif; ?>
                </ul>
                <!--END RD Navbar Nav-->
              </div>
            </div>
          </nav>
        </div>
        <!--END RD Navbar-->



      </header>
      <!--
      ========================================================
                              CONTENT
      ========================================================
      -->
      <main class="page-content undefined">
        <section class="text-left well">
          <div class="container container-wide">
            <div class="row">
              <div class="col-xs-12 well border-bottom">
                <h1 class="well-bottom">Mentions légales</h1>
                <p>PAPARAZZA SASU<br/>
                    2 rue Jeanne d'arc<br/>
                    51360 VAL DE VESLE<br/>
                    capital 1000 euros<br/>
                    contact@paparazza.fr<br/>
                    tél 03 26 02 18 53<br/>
                    RCS REIMS 804 387 355<br/>
                    TVA intracommunautaire FR 54 804387355
                </p>
                <p class="inset-1">déclaration CNIL N°1801875v0</p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <!--
      ========================================================
                              FOOTER
      ========================================================
      -->

      <?php include('pages/footer.phtml'); ?>

    </div>
    <!--Core Scripts-->
    <script src="<?= url('ressources/js/core.min.js')?>"></script>
    <!--jQuery (necessary for Bootstrap's JavaScript plugins)-->
    <!--Include all compiled plugins (below), or include individual files as needed-->
    <script src="<?= url('ressources/js/bootstrap.min.js')?>"></script>
    <!--Additional Functionality Scripts-->
    <script src="<?= url('ressources/js/script.js')?>"></script>
    <script src="<?= url('ressources/js/overwriting.js')?>"></script>
  </body>
</html>
