<footer class="page-footer footer-centered text-center bg-dark">
  <section class="footer-content">
    <div class="container container-wide">
      <div class="navbar-brand"><a href="index.html">PAPARAZZA</a></div>
      <address><?= $infos->getAdress1() ?><br>
        <?php if (!empty($infos->getCompltAdress1())): ?>
            <?= $infos->getCompltAdress1() ?><br>
        <?php endif; ?><?= $infos->getCity1() ?>, <?= $infos->getCp1() ?>
      </address><address>
          <a href="callto:#"><?= $infos->getTel1() ?></a><br>
          <?php if (!empty($infos->getTel2())): ?>
              <a href="callto:#"><?= $infos->getTel2() ?></a><br>
          <?php endif; ?>
          <a href="mailto:#"><?= $infos->getEmail() ?></a>
      </address>
      <ul class="list-inline">
        <li><a href="https://www.instagram.com/paparazza_lyon" class="fa-instagram"></a></li>
        <li><a href="#" class="fa-linkedin"></a></li>
        <li><a href="https://fr-fr.facebook.com/bornesconnectees" class="fa-facebook"></a></li>
      </ul>
    </div>
  </section>
  <section class="rights">
    <p class="copyright">Paparazza <span id="copyright-year"></span> All Rights Reserved | <a href="<?= url('mentions-legales') ?>" class="text-primary">Mentions légales</a></p>
  </section>
</footer>
