<footer class="page-footer footer-centered text-center bg-dark">
  <section class="footer-content">
    <div class="container container-wide">
      <div class="navbar-brand"><a href="index.html">PAPARAZZA</a></div>
      <address>Pôle Pixel<br>26 rue Emile Decorps<br>Villeurbanne, 69100</address>
      <address><a href="callto:#">06 70 53 48 90<br></a><a href="mailto:#">contact@paparazza.fr</a></address>
      <ul class="list-inline">
        <li><a href="https://www.instagram.com/paparazza_lyon" class="fa-instagram"></a></li>
        <li><a href="#" class="fa-linkedin"></a></li>
        <li><a href="https://fr-fr.facebook.com/bornesconnectees" class="fa-facebook"></a></li>
      </ul>
    </div>
  </section>
  <section class="rights">
    <p class="copyright">Paparazza<span id="copyright-year"></span> All Rights Reserved <a href="terms.html" class="text-primary">Terms of Use</a> | <a href="terms.html" class="text-primary">Privacy Policy</a></p>
  </section>
</footer>
