<section id="gallery" class="bg-dark text-center well well-sm">
    <div class="container container-wide">
        <div class="row">
            <h1>GALERIE PHOTO</h1>
            <hr>
            <div data-editable data-name="gallery_text">
                <!-- editable gallery_text -->
<p>
    sdfsdf
</p>
<!-- endeditable gallery_text -->
            </div>
              <?php if(isset($imgs)): ?>
                <div class="row inset-1">
                  <div data-lightbox="gallery" class="flow-offset-1">
                    <div id="galleryImg">
                      <?php foreach ($imgs as $img):?>
                          <div class="col-xs-6 col-md-3">
                              <a href="<?= url('uploads/gallery/' . $img->getImgSrc()) ?>" data-lightbox="image" title="<?php $img->getDescription() ?>">
                                  <img src="<?= url('uploads/gallery/' . $img->getImgSrc()) ?>" alt="Image 1"/>
                              </a>
                          </div>
                      <?php endforeach; ?>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 col-md-push-3">
                    <?php for($i = 1; $i <= $numberOfPages; $i++): ?>
                      <a href="?page=<?= $i ?>"class="badge btn-default pagination" id="<?= $i ?>"><?= $i ?></a>
                    <?php endfor; ?>
                  </div>
                </div>
              <?php endif; ?>
        </div>
    </div>
</section>
