<section id="gallery" class="bg-dark text-center well well-sm">
    <div class="container container-wide">
        <div class="row">
            <h1>GALERIE PHOTO</h1>
            <hr>
            <p class="container text-center well-bottom">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <?php if(isset($imgs)): ?>
                <div data-lightbox="gallery" class="flow-offset-1">
                    <?php foreach ($imgs as $img):?>
                        <div class="col-xs-6 col-md-3">
                            <a href="<?= url('uploads/gallery/' . $img->getImgSrc()) ?>" data-lightbox="image" title="<?= esc($img->getDescription()) ?>">
                                <img src="<?= url('uploads/gallery/' . $img->getImgSrc()) ?>" alt="Image 1"/>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

        </div>
    </div>
</section>
