<section class="well well-sm text-center">
    <div class="container container-wide">
        <div class="text-center well-bottom" data-editable data-name="partenaires_text">
            <!-- editable partenaires_text -->
            <h2>Ils ont boosté leurs évènements</h2>
            <hr>
            <!-- editable partenaires_text -->
        </div>
      <ul class="flex-list well-top text-center">
          <!-- le template propose de faire une page clients, on garde ou pas ?? -->
        <li><a href="clients.html"><img src="<?= url('ressources/images/client-1.png')?>" alt="" class="client"></a></li>
        <li><a href="clients.html"><img src="<?= url('ressources/images/client-2.jpg')?>" alt="" class="client"></a></li>
        <li><a href="clients.html"><img src="<?= url('ressources/images/client-3.jpg')?>" alt="" class="client"></a></li>
        <li><a href="clients.html"><img src="<?= url('ressources/images/client-4.jpg')?>" alt="" class="client"></a></li>
      </ul>
    </div>
  </section>
