
        <section id="prestations" class="well well-sm text-center">
          <h2 class="text-center inset-1">Nos Prestations</h2>

          <hr>
          <div class="container container-wide">
            <div class="row row-no-gutter">
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2>location borne photo</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>forfait 3 heures</li>
                    <li>forfait journée</li>
                    <li>forfait soirée</li>
                    <li>forfait week-end</li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2> location borne hashtag</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>forfait journée ou soirée</li>
                    <li>impression illimitée</li>
                    <li>1 ou 2 hashtags dédiés à l'événement</li>
                    <li>Envoi simultané dans un album de votre Facebook</li>
                    <li></li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2> location imprimante</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>Nos imprimantes thermiques peuvent être louées, devis sur demande.</li>
                    <li></li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
              <div class="col-sm-6 col-lg-3">
                <div class="bg-light-gray pricing-box">
                  <h2> vente de bornes</h2>
                  <hr>
                  <ul class="list-unstyled-2 text-uppercase text-bold">
                    <li>renseignement et prix sur demande</li>
                    <li></li>
                  </ul>
                  <hr><a href="#contact" class="btn btn-default">demander <br />un devis</a>
                </div>
              </div>
            </div>
          </div>
        </section>
