<section class="well text-center">
    <h2 class="text-center">Rendez vos invités actifs en leur proposant une borne adaptée à votre événement :</h2>
    <hr>
  <div class="container container-wide  text-sm-left">
    <div class="row flow-offset-1">
      <div class="row clearfix">
          <div class="col-sm-6 col-md-4 col-md-offset-2">
            <div data-wow-duration="2s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">
              <div class="box__left"><span class="icon icon-lg icon-primary fa-futbol-o"></span></div>
              <div class="box__body">
                <h4 class="text-bold inset-1"><a href="#digisport">Mur Digital 2.0</a></h4>
                <p class="small text-darker">Attirez du public sur votre stand avec nos jeux sportif sur mur digital.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-md-offset-2">
              <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                <div class="box__left"><span class="icon icon-lg icon-primary fa-hashtag"></span></div>
                <div class="box__body">
                  <h4 class="text-bold inset-1"><a href="#hashtag">Borne Hashtag</a></h4>
                  <p class="small text-darker">Basée sur le selfie envoyé par Instagram et Twitter sur un hashtag réservé à votre événement, imprime les photos en format polaroid personnalisé.</p>
                </div>
              </div>
          </div>
      </div>
      <div class="row flow-offset-1">
          <div class="col-sm-6 col-md-4">
            <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
              <div class="box__left"><span class="icon icon-lg icon-primary fa-camera"></span></div>
              <div class="box__body">
                <h4 class="text-bold inset-1"><a href="#pĥoto">Borne Selfy Station</a></h4>
                <p class="small text-darker">Véritable studio photo mobile, cette borne photographique imprime sous divers formats, partage par mail et réseaux sociaux.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-md-offset-2">
              <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                <div class="box__left"><span class="icon icon-lg icon-primary fa-book"></span></div>
                <div class="box__body">
                  <h4 class="text-bold inset-1"><a href="#livre-or">Livre d'or Numérique</a></h4>
                  <p class="small text-darker">Une tablette numérique qui passe de main en main pour faire une photo, une vidéo, écrire un message sur l'écran tactile.</p>
                </div>
              </div>
          </div>
      </div>
      <div class="row flow-offset-1">
        <div class="row clearfix">
            <div class="col-sm-6 col-md-4 col-md-offset-2">
              <div data-wow-duration="2s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">
                <div class="box__left"><span class="icon icon-lg icon-primary fa-music"></span></div>
                <div class="box__body">
                  <h4 class="text-bold inset-1"><a href="#jukeback">Jukeback</a></h4>
                  <p class="small text-darker">Le retour d'un mythe ! Faites participer vos clients à l'ambiance musicale de votre établissement. Contrôlez à distance et informez vos clients via une appli mobile personnalisable.</p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-4 col-md-offset-2">
                <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                  <div class="box__left"><span class="icon icon-lg icon-primary fa-hashtag"></span></div>
                  <div class="box__body">
                    <h4 class="text-bold inset-1"><a href="#">Lorem Ipsum</a></h4>
                    <p class="small text-darker">Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                  </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</section>
