<!-- PRODUCTS SECTION -->

<section id="products" class="well well-sm text-center bg-dark">
  <div class="container container-wide">

      <h2 class="text-center inset-1">Nos Produits</h2>

      <hr>

      <article id="hashtag" class="blog-post row overflow-h offset-2">

          <div class="col-md-4 bg-dark-blue-2 article-column-img">
            <img src="<?= url('ressources/images/borne_hashtag.jpg')?>" class="img-wide-var-2 bordered products"alt="">
          </div>

          <div class="col-md-8 caption bg-white article-column-text">
            <h3 class="text-left text-base">Borne Hashtag</h3>
            <p class="text-left text-darker">Faites un selfie</p>
            <p class="text-left text-darker">Envoyez le par instagram ou twitter sur le # réservé à l'événement</p>
            <p class="text-left text-darker">Sélectionnez votre photo sur l'écran de la borne HASHTAG</p>
            <p class="text-left text-darker">Imprimez la en format polaroid personnalisé</p>
            <p class="text-left text-darker inset-1">Boostez votre événement, développez la notoriété de votre entreprise, augmentez votre présence digitale.</p>
            <p class="text-left text-darker">Faites de vos invités les reporters de votre événement...</p>
            <p class="text-left text-darker">La borne Hashtag s'adresse plus particulièrement aux événements ayant un grand nombre de participants, aux grandes salles, aux événements extérieurs : marathon, tous événements sportifs, foire exposition...</p>
          </div>
      </article>

    <article id="photo" class="blog-post row overflow-h offset-4">

        <div class="col-md-8 caption bg-white article-column-text">
          <h3 class="text-right text-base">La borne photographique selfy station</h3>
          <p class="text-right text-darker">Le Selfy Station est une borne photographique connectée qui permet d’accueillir un grand nombre de participants ce qui multiplie le plaisir.</p>
          <p class="text-right text-darker">Placé devant un fond de studio, il vous permet de vous retrouver devant un photocall.</p>
          <p class="text-right text-darker">Cette borne s'adresse plus particulièrement aux : mariages, anniversaires, team buildings, journées portes ouvertes...</p>
          <p class="text-right text-darker inset-1">Véritable condensé technique, chaque Selfy Station de Paparazza est équipé du meilleur matériel pour prendre des clichés de qualité.</p>
          <p class="text-right text-darker">Seul ou en groupe, vous prenez de 1 à 4 poses à chaque utilisation, vous imprimez vos photos, vous les envoyez par mail, Facebook, Twitter, Pinterest et ce, en illimité.</p>
          <p class="text-right text-darker">Les écrans successifs et les photos sont personnalisés selon vos souhaits et, surtout, surtout...</p>
          <p class="text-right text-darker">Tous les participants passent un extraordinaire moment de rire et de partage.</p>
          <p class="text-right text-darker"><strong>La borne PHOTOGRAPHIQUE SELFY STATION est totalement addictive, vous y reviendrez sans cesse.</strong></p>
        </div>

        <div class="col-md-4 bg-dark-blue-2 article-column-img">
          <img src="<?= url('ressources/images/borne_photo_1.jpg')?>" class="img-wide-var-2 bordered products"alt="">
        </div>

    </article>

    <article id="livre-or" class="blog-post row overflow-h offset-4">

      <div class="col-md-4 bg-dark-blue-2 article-column-img">
        <img src="<?= url('ressources/images/livre_couv.jpg')?>" class="img-wide-var-2 bordered products"alt="">
      </div>

      <div class="col-md-8 caption bg-white article-column-text">
        <h3 class="text-left text-base">Le livre d'or numérique</h3>
        <p class="text-left text-darker">Imaginez une tablette qui passe de main en main</p>
        <p class="text-left text-darker">Elle vous permet de prendre une photo, une vidéo, d'écrire un message sur son écran tactile et de recommencer autant que vous voulez.</p>
        <p class="text-left text-darker">Pour un mariage, une inauguration ou n'importe quel événement,  vous aurez plaisir à récupérer ce livre d'or numérique et à le feuilleter,  vous laissant, ainsi,  le plus vivant des souvenirs.</p>
      </div>

    </article>

      <article id="digisport" class="blog-post row offset-4">

          <div class="col-md-12 bg-dark-blue-2">

            <div class="video-container">

              <iframe src="https://www.youtube.com/embed/cTSjyXL4_MQ" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>


          <div class="col-md-12 caption bg-white">
            <h3 class="text-left text-base">Digi-Sports 2.0</h3>
            <p class="text-left text-darker">Créez du passage sur votre stand avec l'animation DIGI-SPORTS 2.0</p>
            <p class="text-left text-darker">Mur digital avec habillage à votre marque, choix de jeux, écran de score.</p>
          </div>

      </article>

  </div>

</section>
