<!-- PRODUCTS SECTION -->

<section id="products" class="well well-sm text-center bg-dark">
  <div class="container container-wide">

      <h2 class="text-center inset-1">Nos Produits</h2>

      <hr>

      <article id="digisport" class="blog-post row offset-4">

          <div class="col-md-12 bg-dark-blue-2">

            <div class="video-container">

              <iframe src="https://www.youtube.com/embed/z03J5ev2jg4" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>


          <div class="col-md-12 caption bg-white">
            <h3 class="text-left text-base">mur digital 2.0</h3>
            <p class="text-left text-darker">Créez du passage sur votre stand avec l'animation DIGI-SPORTS 2.0</p>
            <p class="text-left text-darker">Mur digital avec habillage à votre marque, choix de jeux, écran de score.</p>
          </div>

      </article>

      <article id="hashtag" class="blog-post row overflow-h offset-2">

          <div data-lightbox="gallery" class="col-md-4 bg-dark-blue-2 article-column-img">
            <a href="<?= url('ressources/images/borne_hashtag.jpg')?>" data-lightbox="image">
                <img src="<?= url('ressources/images/borne_hashtag.jpg')?>" class="img-wide-var-2 bordered products" alt="">
            </a>
            <a href="<?= url('ressources/images/borne_hashtag.jpg')?>" data-lightbox="image" style="display:none">
                <img src="<?= url('ressources/images/borne_hashtag.jpg')?>" class="img-wide-var-2 bordered products" alt="">
            </a>
            <a href="<?= url('ressources/images/borne_hashtag.jpg')?>" data-lightbox="image" style="display:none">
                <img src="<?= url('ressources/images/borne_hashtag.jpg')?>" class="img-wide-var-2 bordered products" alt="">
            </a>
            <a href="<?= url('ressources/images/borne_hashtag.jpg')?>" data-lightbox="image" style="display:none">
                <img src="<?= url('ressources/images/borne_hashtag.jpg')?>" class="img-wide-var-2 bordered products" alt="">
            </a>
          </div>

          <div class="col-md-8 caption bg-white article-column-text">
            <h3 class="text-left text-base">Borne Hashtag</h3>
            <p class="text-left text-darker">Faites un selfie</p>
            <p class="text-left text-darker">Envoyez le par instagram ou twitter sur le # réservé à l'événement</p>
            <p class="text-left text-darker">Sélectionnez votre photo sur l'écran de la borne HASHTAG</p>
            <p class="text-left text-darker">Imprimez la en format polaroid personnalisé</p>
            <p class="text-left text-darker inset-1">Boostez votre événement, développez la notoriété de votre entreprise, augmentez votre présence digitale.</p>
            <p class="text-left text-darker">Faites de vos invités les reporters de votre événement...</p>
            <p class="text-left text-darker">La borne Hashtag s'adresse plus particulièrement aux événements ayant un grand nombre de participants, aux grandes salles, aux événements extérieurs : marathon, tous événements sportifs, foire exposition...</p>
          </div>
      </article>

    <article id="photo" class="blog-post row overflow-h offset-4">

        <div class="col-md-8 caption bg-white article-column-text">
          <h3 class="text-right text-base">La borne photographique selfy station</h3>
          <p class="text-right text-darker">Le Selfy Station est une borne photographique connectée qui permet d’accueillir un grand nombre de participants ce qui multiplie le plaisir.</p>
          <p class="text-right text-darker">Placé devant un fond de studio, il vous permet de vous retrouver devant un photocall.</p>
          <p class="text-right text-darker">Cette borne s'adresse plus particulièrement aux : mariages, anniversaires, team buildings, journées portes ouvertes...</p>
          <p class="text-right text-darker inset-1">Véritable condensé technique, chaque Selfy Station de Paparazza est équipé du meilleur matériel pour prendre des clichés de qualité.</p>
          <p class="text-right text-darker">Seul ou en groupe, vous prenez de 1 à 4 poses à chaque utilisation, vous imprimez vos photos, vous les envoyez par mail, Facebook, Twitter, Pinterest et ce, en illimité.</p>
          <p class="text-right text-darker">Les écrans successifs et les photos sont personnalisés selon vos souhaits et, surtout, surtout...</p>
          <p class="text-right text-darker">Tous les participants passent un extraordinaire moment de rire et de partage.</p>
          <p class="text-right text-darker"><strong>La borne PHOTOGRAPHIQUE SELFY STATION est totalement addictive, vous y reviendrez sans cesse.</strong></p>
        </div>

        <div class="col-md-4 bg-dark-blue-2 article-column-img" data-lightbox="gallery">
          <a data-lightbox="image" href="<?= url('ressources/images/borne_photo_1.jpg')?>"><img src="<?= url('ressources/images/borne_photo_1.jpg')?>" class="img-wide-var-2 bordered products"alt=""></a>
          <a data-lightbox="image" href="<?= url('ressources/images/borne_photo_1.jpg')?>"><img src="<?= url('ressources/images/borne_photo_1.jpg')?>" class="img-wide-var-2 bordered products"alt="" style="display:none"></a>
          <a data-lightbox="image" href="<?= url('ressources/images/borne_photo_1.jpg')?>"><img src="<?= url('ressources/images/borne_photo_1.jpg')?>" class="img-wide-var-2 bordered products"alt="" style="display:none"></a>
          <a data-lightbox="image" href="<?= url('ressources/images/borne_photo_1.jpg')?>"><img src="<?= url('ressources/images/borne_photo_1.jpg')?>" class="img-wide-var-2 bordered products"alt="" style="display:none"></a>
        </div>

    </article>

    <article id="livre-or" class="blog-post row overflow-h offset-4">

      <div class="col-md-4 bg-dark-blue-2 article-column-img" data-lightbox="gallery">
        <a data-lightbox="image" href="<?= url('ressources/images/livre_couv.jpg')?>"><img src="<?= url('ressources/images/livre_couv.jpg')?>" class="img-wide-var-2 bordered products"alt=""></a>
        <a data-lightbox="image" href="<?= url('ressources/images/livre_couv.jpg')?>"><img src="<?= url('ressources/images/livre_couv.jpg')?>" class="img-wide-var-2 bordered products"alt="" style="display:none"></a>
        <a data-lightbox="image" href="<?= url('ressources/images/livre_couv.jpg')?>"><img src="<?= url('ressources/images/livre_couv.jpg')?>" class="img-wide-var-2 bordered products"alt="" style="display:none"></a>
        <a data-lightbox="image" href="<?= url('ressources/images/livre_couv.jpg')?>"><img src="<?= url('ressources/images/livre_couv.jpg')?>" class="img-wide-var-2 bordered products"alt="" style="display:none"></a>
      </div>

      <div class="col-md-8 caption bg-white article-column-text">
        <h3 class="text-left text-base">Le livre d'or numérique</h3>
        <p class="text-left text-darker">Imaginez une tablette qui passe de main en main</p>
        <p class="text-left text-darker">Elle vous permet de prendre une photo, une vidéo, d'écrire un message sur son écran tactile et de recommencer autant que vous voulez.</p>
        <p class="text-left text-darker">Pour un mariage, une inauguration ou n'importe quel événement,  vous aurez plaisir à récupérer ce livre d'or numérique et à le feuilleter,  vous laissant, ainsi,  le plus vivant des souvenirs.</p>
      </div>

    </article>

    <article id="jukeback" class="blog-post row overflow-h offset-2">

        <div class="col-md-8 caption bg-white article-column-text">
          <h3 class="text-right text-base">Borne Jukeback</h3>
          <h4 class="text-right text-base inset-1">JUKEBACK SIGNE LE RETOUR D'UN MYTHE !</h4>
          <p class="text-right text-darker">LE NOUVEL OUTIL LUDIQUE</p>
          <p class="text-right text-darker">Jukeback permet à vos clients de participer à l'ambiance musicale de votre établissement. Des jeux proposés offrent une interactivité entre vos barmans et votre clientèle. Grâce à l'application mobile*, vos clients peuvent récupérer les informations sur les chansons diffusées et voter pour ces dernières.</p>

          <h4 class="text-right text-base inset-1">JUKEBACK VOUS FAIT GAGNER DU TEMPS !</h4>
          <p class="text-right text-darker">UNE AIDE PRÉCIEUSE POUR VOS BARMANS</p>
          <p class="text-right text-darker">Gardez le contrôle de la diffusion musicale via une interface web très simple. En cas de rush, vos barmans peuvent activer le << mode programmation >> en 1 clic et lancer de multiples playlists. Ainsi, vos barmans focalisent leur énergie sur d'autres priorités.</p>

          <h4 class="text-right text-base inset-1">JUKEBACK VOUS AIDE À COMMUNIQUER !</h4>
          <p class="text-right text-darker">COMMUNIQUEZ AVEC VOS CLIENTS</p>
          <p class="text-right text-darker">Partagez chacun de vos événements grâce à l'application mobile Jukeback disponible gratuitement pour iPhone/iPad et Android. Attirez de nouveaux clients en affichant toutes les informations essentielles de votre établissement sur l'application.</p>

          <h4 class="text-right text-base inset-1">JUKEBACK EST À VOTRE IMAGE !</h4>
          <p class="text-right text-darker">DÉMARQUEZ-VOUS !</p>
          <p class="text-right text-darker">Exploitez toutes les possibilités offertes par Jukeback pour obtenir une différenciation poussée de votre établissement. Ajoutez votre logo* sur la borne Jukeback et profitez de playlists personnalisées.</p>

          <h4 class="text-right text-base inset-1">JUKEBACK VOUS RAPPORTE !</h4>
          <p class="text-right text-darker">AUGMENTEZ VOTRE CHIFFRE D'AFFAIRES !</p>
          <p class="text-right text-darker">L'offre Jukeback comprend la location, l'assistance et la maintenance. Récupérez la totalité des dépenses de vos clients via le monnayeur de la borne Jukeback. Renforcez l'attractivité de votre bar et ainsi le volume de consommation de votre clientèle.</p>

        </div>

        <div data-lightbox="gallery" class="col-md-4 bg-dark-blue-2 article-column-img">
          <a href="<?= url('ressources/images/borne_jukeback.jpg')?>" data-lightbox="image">
              <img src="<?= url('ressources/images/borne_jukeback.jpg')?>" class="img-wide-var-2 bordered products long" alt="">
          </a>
          <a href="<?= url('ressources/images/borne_jukeback_2.jpg')?>" data-lightbox="image" style="display:none">
              <img src="<?= url('ressources/images/borne_jukeback_2.jpg')?>" class="img-wide-var-2 bordered products" alt="">
          </a>
          <a href="<?= url('ressources/images/borne_jukeback_3.jpg')?>" data-lightbox="image" style="display:none">
              <img src="<?= url('ressources/images/borne_jukeback_3.jpg')?>" class="img-wide-var-2 bordered products" alt="">
          </a>
          <a href="<?= url('ressources/images/borne_jukeback_4.png')?>" data-lightbox="image" style="display:none">
              <img src="<?= url('ressources/images/borne_jukeback_4.png')?>" class="img-wide-var-2 bordered products" alt="">
          </a>
        </div>

    </article>


  </div>

</section>
