<section class="well well-sm page-sample">
  <div class="container container-wide">

    <h2 class="text-center">Boostez vos événements avec une borne connectée ou un jeu DIGI-SPORTS 2.0</h2>


      <!-- Mosaique produits -->
      <div class="mosaique row row-no-gutter offset-2">
          <div class="col-xs-6 col-sm-6 col-md-3">
            <div class="img-thumbnail text-center"><a href="#hashtag" class="mfp-image"><img src="<?= url('ressources/images/hashtag_jaune.png')?>" alt="hashtag_jaune" class="img-wide">
                <div class="caption">
                  <h1>BORNE HASHTAG</h1>
                  <p>En savoir plus</p>
                </div><span class="overlay"></span></a></div>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-3">
            <div class="img-thumbnail text-center"><a href="#photo" class="mfp-image"><img src="<?= url('ressources/images/photo_bleu.png')?>" alt="camera bleue" class="img-wide">
                <div class="caption">
                  <h1>BORNE SELFY STATION</h1>
                  <p>En savoir plus</p>
                </div><span class="overlay"></span></a></div>
          </div>
        <div class="col-xs-6 col-sm-6 col-md-3">
          <div class="img-thumbnail text-center"><a href="#livre-or" class="mfp-image"><img src="<?= url('ressources/images/livre_orange.png')?>" alt="livre orange" class="img-wide">
              <div class="caption">
                <h1>LIVRE D'OR NUMERIQUE</h1>
                <p>En savoir plus</p>
              </div><span class="overlay"></span></a></div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-3">
          <div class="img-thumbnail text-center"><a href="#digisport" class="mfp-image"><img src="<?= url('ressources/images/sport_violet.png')?>" alt="ballon violet" class="img-wide">
              <div class="caption">
                <h1>DIGISPORT</h1>
                <p>En savoir plus</p>
              </div><span class="overlay"></span></a></div>
        </div>
      </div>
  </div>
</section>
