<section id="selling" class="text-center well bg-dark">
  <div class="container container-wide">
    <div class="col-xs-12 border-bottom well">
      <h2 class="text-center">Vente de Matériel</h2>
      <hr class="text-center">
      <div class="row">
        <div class="col-sm-5">
          <!--Tabs-->
          <ul id="myTabs2" role="tablist" class="nav nav-tabs vertical-tabs text-center">
            <li role="presentation" class="active"><a href="#vtab0" aria-controls="vtab0" role="tab" class="fa-television">Borne Photo Type Caisse de Transport<span class="fa-chevron-right"></span></a></li>
            <li role="presentation"><a href="#vtab1" aria-controls="vtab1" role="tab" class="fa-thumbs-up">Le slim<span class="fa-chevron-right"></span></a></li>
          </ul>
        </div>
        <div class="col-sm-offset-1 col-sm-6">
          <!--Tab panes-->
          <div class="tab-content vertical-tabs text-sm-left">
            <div role="tabpanel" id="vtab0" class="tab-pane active fade in blog-post">
              <div class="bg-dark-blue-2">
                <img src="<?= url('ressources/images/ct27.png')?>" alt="borne ct27" class="verticaly-centered bordered products">
              </div>
              <ul class="inset-2 text-darker caption bg-white article-column-text">NEUF - Réf CT27
                <li>Structure 2 étages séparables type caisse de transport</li>
                <li>Appareil photo Canon 700D </li>
                <li>Imprimante DNP DS620 </li>
                <li>Flash 180w</li>
                <li>Pc tout en un Lenovo ou équivalent, écran tactile 21.5 pouces</li>
              </ul>
            </div>
            <div role="tabpanel" id="vtab1" class="tab-pane fade blog-post">
              <div class="bg-dark-blue-2">
                <img src="<?= url('ressources/images/slim-1.png')?>" alt="borne SLIM" class="verticaly-centered bordered products">
              </div>
              <ul class="inset-2 text-darker caption bg-white article-column-text">NEUF - Ref
                <li>Le SLIM est un photo booth avec ipad et la solution la plus facile de proposer un kiosque photo.</li>
                <li class="inset-1">Structure en acier massif</li>
                <li>Panneau lumineux rétroéclairé par LED</li>
                <li>Ouïes pour haut-parleur et ventilation</li>
                <li>Panneau arrière fermé à clef afin de stocker l’ipad en toute sécurité</li>
                <li>Personnalisation des photos</li>
                <li>Filtres</li>
                <li>Photos simple et multiples</li>
                <li>Partage par mail et réseaux sociaux</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
