<section>
  <!--Swiper-->
  <?php if(isset($slides)): ?>
    <div data-autoplay="5000" data-slide-effect="fade" data-loop="false" data-height="36,45833333333333%" data-min-height="400px" class="swiper-container swiper-slider swiper-container-horizontal swiper-container-fade" style="height: 400px;">
      <div class="container container-wide slider-container">
        <div class="jumbotron text-center bg-btn">
          <h1 data-wow-duration="2s" class="wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">PAPARAZZA<small data-wow-duration="2s" class="wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">Boostez vos évènements</small></h1>
          <p data-wow-duration="2s" class="big wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;"></p>
        </div>
      </div>
      <div class="swiper-wrapper" style="transition-duration: 0ms;">
        <?php foreach($slides as $slide): ?>
          <div data-slide-bg="<?= url('uploads/slider/' . $slide->getImgSrc())?>" class="swiper-slide swiper-slide-prev" style="background-image: url(&quot;images/slide-1.jpg&quot;); background-size: cover; width: 791px; opacity: 1; transform: translate3d(0px, 0px, 0px); transition-duration: 0ms;">
            <div class="swiper-slide-caption"></div>
          </div>
        <?php endforeach; ?>
      </div>
      <!--Swiper Pagination-->
      <div class="swiper-pagination swiper-pagination-clickable"><span class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet swiper-pagination-bullet-active"></span><span class="swiper-pagination-bullet"></span></div>
    </div>
  <?php endif; ?>
</section>
