<h1>SUper titre</h1>

<p>bisoubisou</p>
<!-- editable jukeback -->
<h3 class="text-right text-base">
    Borne Jukeback
</h3>
<h4 class="text-right text-base inset-1">
    JUKEBACK SIGNE LE RETOUR D'UN MYTHE !
</h4>
<p class="text-right text-darker">
    LE NOUqscqVEL OUTIL LUDIQUE
</p>
<p class="text-right text-darker">
    Jukeback permet à vos clients de&nbsp;par
</p>
<h4 class="text-right text-base inset-1">
    xwcJUKEBACK VpigdsfsjfsqcqgsdOUS FAIT GAGNER DU TEMPS !
</h4>
<p class="text-right text-darker">
    UNE AIDE PRÉCIEUSE POUR VOS BARMANS
</p>
<p class="text-right text-darker">
    Gardez le&nbsp;contrôle de la diffusion musicale&nbsp;via une&nbsp;interface&nbsp;web trwcès&nbsp;simple.&nbsp;En cas de rush, vos barmans peuvent activer le &lt;&lt;&nbsp;mode programmation dfocalisent leur énergie&nbsp;sur d'autres priorités.
</p>
<h4 class="text-right text-base inset-1">
    JUKEBACK VOUS AIDE À COMMUNIQUER !
</h4>
<p class="text-right text-darker">
    COMMUNIQUEZ AVEC VOS CLIENTS
</p>
<p class="text-right text-darker">
    Partagez&nbsp;chacun de vos&nbsp;événements&nbsp;grâce à l'application mobile Jukeback disponible&nbsp;gratuitement&nbsp;pour&nbsp;iPhone/iPad&nbsp;et&nbsp;Android.&nbsp;Attirez de nouveaux clients&nbsp;en affichant toutes les informations essentielles de votre établissement sur l'application.
</p>
<h4 class="text-right text-base inset-1">
    JUKEBACK EST À VOTRE IMAGE !
</h4>
<p class="text-right text-darker">
    DÉMARQUEZ-VOUS !
</p>
<p class="text-right text-darker">
    Exploitez toutes les possibilités&nbsp;offertes par Jukeback pour obtenir une&nbsp;différenciation poussée de votre établissement. Ajoutez&nbsp;votre logo*&nbsp;sur la borne Jukeback et profitez de&nbsp;playlists personnalisées.
</p>
<h4 class="text-right text-base inset-1">
    JUKEBACK VOUS RAPPORTE !
</h4>
<p class="text-right text-darker">
    AUGMENTEZ VOTRE CHIFFRE D'AFFAIRES !
</p>
<p class="text-right text-darker">
    L'offre Jukeback comprend&nbsp;la location, l'assistance et la maintenance.&nbsp;Récupérez la totalité des dépenses de vos clients&nbsp;via le monnayeur de la borne Jukeback.&nbsp;Renforcez l'attractivité&nbsp;de votre bar et ainsi&nbsp;le volume de consommation&nbsp;de votre clientèle.
</p>
<!-- endeditable jukeback -->

<footer>c'est le pied !</footer>
