<h1>SUper titre</h1>

<p>bisoubisou</p>
<!-- editable jukeback -->
<h3 class="text-right text-base">
    Borne Jukeback
</h3>
<h4 class="text-right text-base inset-1">
    JUKEBACK SIGNE LE RETOUR D'UN MYTHE !
</h4>
<p class="text-right text-darker">
    LE NOUVEL OUTIL LUDIQUE
</p>
<p class="text-right text-darker">
    Jukeback permet à vos clients de&nbsp;participer à l'ambiance musicale&nbsp;de votre établissement.&nbsp;Des jeux&nbsp;proposés offrent une&nbsp;interactivité&nbsp;entre vos barmans et votre clientèle. Grâce à l'application mobile*, vos clients peuvent récupérer les&nbsp;informations&nbsp;ssdfssdfsdfsdfdfqcur les&nbsp;chansqscqscqcqons diffusées&nbsp;et&nbsp;voter&nbsp;pour ces dernières.
</p>
<h4 class="text-right text-base inset-1">
    JUKEBACK VOUS FcqsqcqcqcAIT GAGNER DU TEMPS XXXXXXX!
</h4>
<p class="text-right text-darker">
    UNE AIDE PRÉCIEUSE POUR VOS BARMANS
</p>
<p class="text-right text-darker">
    Gardez le&nbsp;contrôle de la diffusion musicale&nbsp;via une&nbsp;interface&nbsp;web très&nbsp;simple.&nbsp;En cas de rush, vos barmans peuvent activer le &lt;&lt;&nbsp;mode programmation&nbsp;&gt;&gt; en&nbsp;1 clic&nbsp;et&nbsp;lancer&nbsp;de&nbsp;multiples playlists. Ainsi, vos barmans&nbsp;focalisent leur énergie&nbsp;sur d'autres priorités.
</p>
<h4 class="text-right text-base inset-1">
    JUKEBACK VOUS AIDE À COMMUNIQUER !
</h4>
<p class="text-right text-darker">
    COMMUNIQUEZ AVEC VOS CLIENTS
</p>
<p class="text-right text-darker">
    Partagez&nbsp;chacun de vos&nbsp;événements&nbsp;grâce à l'application mobile Jukeback disponible&nbsp;gratuitement&nbsp;pour&nbsp;iPhone/iPad&nbsp;et&nbsp;Android.&nbsp;Attirez de nouveaux clients&nbsp;en affichant toutes les informations essentielles de votre établissement sur l'application.
</p>
<h4 class="text-right text-base inset-1">
    JUKEBACK EST À VOTRE IMAGE !
</h4>
<p class="text-right text-darker">
    DÉMARQUEZ-VOUS !
</p>
<p class="text-right text-darker">
    Exploitez toutes les possibilités&nbsp;offertes par Jukeback pour obtenir une&nbsp;différenciation poussée de votre établissement. Ajoutez&nbsp;votre logo*&nbsp;sur la borne Jukeback et profitez de&nbsp;playlists personnalisées.
</p>
<h4 class="text-right text-base inset-1">
    JUKEBACK VOUS RAPPORTE !
</h4>
<p class="text-right text-darker">
    AUGMENTEZ VOTRE CHIFFRE D'AFFAIRES !
</p>
<p class="text-right text-darker">
    L'offre Jukeback comprend&nbsp;la location, l'assistance et la maintenance.&nbsp;Récupérez la totalité des dépenses de vos clients&nbsp;via le monnayeur de la borne Jukeback.&nbsp;Renforcez l'attractivité&nbsp;de votre bar et ainsi&nbsp;le volume de consommation&nbsp;de votre clientèle.
</p>
<!-- endeditable jukeback -->


<!-- editable livreOr -->
<h3 class="text-left text-base">
    Le livre d'or numérique
</h3>
<p class="text-left text-darker">
    Imaginez une tablette qui passe de main en main
</p>
<p class="text-left text-darker">
    Elle vous permet de prendre une photo, une vidéo, d'écrire un message sur son écran tactile et de recommencer asdqvqsdggdsdvgsvdvqqsutant que vous voulez.
</p>
<p class="text-left text-darker">
    Pour un mariage, une inauguration ou n'importe quel événement, vous aurez plaisir à récupérer ce livre d'or numérique et à le feuilleter, vous laissant, ainsi, le plus vivant des souvenirs.
</p>
<!-- endeditable livreOr -->

<footer>c'est le pied !</footer>
