<section class="well well-sm page-sample">
  <div class="container container-wide">

    <div class="row" data-editable data-name="mosaique_title">
        <!-- editable mosaique_title -->
        <h2 class="text-center">Boostez vos événements avec un mur digital 2.0 ou une borne connectée.</h2>
        <!-- endeditable mosaique_title -->
    </div>

      <!-- Mosaique produits -->
      <div class="mosaique row row-no-gutter offset-2 hidden-xs">
          <div class="col-sm-4 col-md-2">
            <div class="img-thumbnail text-center"><a href="#digisport" class="mfp-image"><img src="<?= url('ressources/images/sport_vert.png')?>" alt="ballon" class="img-wide">
                <div class="caption">
                  <h1>MUR DIGITAL</h1>
                  <p>En savoir plus</p>
                </div><span class="overlay"></span></a></div>
          </div>
          <div class="col-sm-4 col-md-2">
            <div class="img-thumbnail text-center"><a href="#hashtag" class="mfp-image"><img src="<?= url('ressources/images/hashtag_jaune.png')?>" alt="hashtag" class="img-wide">
                <div class="caption">
                  <h1>BORNE HASHTAG</h1>
                  <p>En savoir plus</p>
                </div><span class="overlay"></span></a></div>
          </div>
          <div class="col-sm-4 col-md-2">
            <div class="img-thumbnail text-center"><a href="#photo" class="mfp-image"><img src="<?= url('ressources/images/photo_bleu.png')?>" alt="camera" class="img-wide">
                <div class="caption">
                  <h1>BORNE SELFY STATION</h1>
                  <p>En savoir plus</p>
                </div><span class="overlay"></span></a></div>
          </div>
        <div class="col-sm-4 col-md-2">
          <div class="img-thumbnail text-center"><a href="#livre-or" class="mfp-image"><img src="<?= url('ressources/images/livre_orange.png')?>" alt="livre" class="img-wide">
              <div class="caption">
                <h1>LIVRE D'OR NUMERIQUE</h1>
                <p>En savoir plus</p>
              </div><span class="overlay"></span></a></div>
        </div>
        <div class="col-sm-4 col-md-2">
          <div class="img-thumbnail text-center"><a href="#jukeback" class="mfp-image"><img src="<?= url('ressources/images/juke_blanc.png')?>" alt="jukeback" class="img-wide">
              <div class="caption">
                <h1>JUKEBACK</h1>
                <p>En savoir plus</p>
              </div><span class="overlay"></span></a></div>
        </div>
        <div class="col-sm-4 col-md-2">
          <div class="img-thumbnail text-center"><a href="#" class="mfp-image"><img src="<?= url('ressources/images/slim_violet.png')?>" alt="" class="img-wide">
              <div class="caption">
                <h1>LOREM IPSUM</h1>
                <p>En savoir plus</p>
              </div><span class="overlay"></span></a></div>
        </div>
      </div>
  </div>
</section>
