<section class="well text-center">
    <div class="row" data-editable data-name="pastilles_title">
        <!-- editable pastilles_title -->
        <h2 class="text-center">Rendez vos invités actifs en leur proposant une borne adaptée à votre événement :</h2>
        <!-- endeditable pastilles_title -->
    </div>
    <hr>
  <div class="container container-wide  text-sm-left">
    <div class="row flow-offset-1">
      <div class="row clearfix">
          <div class="col-sm-6 col-md-4 col-md-offset-2">
            <div data-wow-duration="2s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">
              <div class="box__left"><span class="icon icon-lg icon-primary fa-futbol-o"></span></div>
              <div class="box__body" data-editable data-name="pastilles_digisport">
                  <!-- editable pastilles_digisport -->
                <h4 class="text-bold inset-1"><a href="#digisport">Mur Digital 2.0</a></h4>
                <p class="small text-darker">Attirez du public sur votre stand avec nos jeux sportif sur mur digital.</p>
                <!-- endeditable pastilles_digisport -->
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-md-offset-2">
              <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                <div class="box__left"><span class="icon icon-lg icon-primary fa-hashtag"></span></div>
                <div class="box__body" data-editable data-name="pastilles_hashtag">
                    <!-- editable pastilles_hashtag -->
                  <h4 class="text-bold inset-1"><a href="#hashtag">Borne Hashtag</a></h4>
                  <p class="small text-darker">Basée sur le selfie envoyé par Instagram et Twitter sur un hashtag réservé à votre événement, imprime les photos en format polaroid personnalisé.</p>
                  <!-- endeditable pastilles_hashtag -->
                </div>
              </div>
          </div>
      </div>
      <div class="row flow-offset-1">
          <div class="col-sm-6 col-md-4">
            <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
              <div class="box__left"><span class="icon icon-lg icon-primary fa-camera"></span></div>
              <div class="box__body" data-editable data-name="pastilles_photo">
                  <!-- editable pastilles_photo -->
                <h4 class="text-bold inset-1"><a href="#pĥoto">Borne Selfy Station</a></h4>
                <p class="small text-darker">Véritable studio photo mobile, cette borne photographique imprime sous divers formats, partage par mail et réseaux sociaux.</p>
                <!-- endeditable pastilles_photo -->
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-md-offset-2">
              <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                <div class="box__left"><span class="icon icon-lg icon-primary fa-book"></span></div>
                <div class="box__body" data-editable data-name="pastilles_livreOr">
                    <!-- editable pastilles_livreOr -->
                  <h4 class="text-bold inset-1"><a href="#livre-or">Livre d'or Numérique</a></h4>
                  <p class="small text-darker">Une tablette numérique qui passe de main en main pour faire une photo, une vidéo, écrire un message sur l'écran tactile.</p>
                  <!-- endeditable pastilles_livreOr -->
                </div>
              </div>
          </div>
      </div>
      <div class="row flow-offset-1">
        <div class="row clearfix">
            <div class="col-sm-6 col-md-4 col-md-offset-2">
              <div data-wow-duration="2s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 2s; animation-name: fadeIn;">
                <div class="box__left"><span class="icon icon-lg icon-primary fa-music"></span></div>
                <div class="box__body" data-editable data-name="pastilles_jukeback">
                    <!-- editable pastilles_jukeback -->
<h4 class="text-bold inset-1">
    <a href="#jukeback">Jukeback</a>
</h4>
<p class="small text-darker">
    Le retour d'un mythe ! Faites participer vos clients à l'ambiance musicale de votre établissement. Contrôlez à distance&nbsp; et informez vos clients via une appli mobile personnalisable.
</p>
<!-- endeditable pastilles_jukeback -->
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-4 col-md-offset-2">
                <div data-wow-duration="1s" class="box-sm box-hover-1 wow fadeIn" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                  <div class="box__left"><span class="icon icon-lg icon-primary fa-hashtag"></span></div>
                  <div class="box__body" data-editable data-name="pastilles_new">
                      <!-- editable pastilles_new -->
<h4 class="text-bold inset-1">
    <a href="#">Lorem Ipsssum</a>
</h4>
<p class="small text-darker">
    Dolor sit amet, consectetur adipisicing elit, sed do eiusmoqsdq sdd tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
</p>
<!-- endeditable pastilles_new -->
                  </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</section>
