<section>
    <form class="text-center" method="post">
        <input type="text" name="name" placeholder="Nom d'utilisateur">
        <input type="password" name="password" placeholder="Mot de passe">
        <input type="submit" value="Envoyer">
    </form>

    <?php if (isset($error)) : ?>
        <div class="bg-error text-center">
                <p><?= $error ?></p>
        </div>
    <?php endif; ?>

</section>
