<h1 class="text-center well well-bottom bg-dark">Gestion des administateurs</h1>
<section class="text-center well">
    <div class="container container-wide bg-white">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 well well-bottom">
                <h3 class="well-bottom">Modifier votre mot de passe</h3>
                <form class="text-center" method="post">

                    <div class="well">
                        <input type="password" class="form-control" data-constraints="@NotEmpty" name="password" placeholder="Mot de passe"
                        <?php if (isset($errors)): ?>
                            value="<?= $password ?>"
                        <?php endif; ?>>
                        <input type="password" class="form-control" data-constraints="@NotEmpty" name="confirmPassword" placeholder="Confirmer mot de passe"
                        <?php if (isset($errors)): ?>
                            value="<?= $password ?>"
                        <?php endif; ?>>
                        <p>Le mot de passe doit contenir 6 caractères minimum dont au moins une lettre et un chiffre.</p>
                    </div>
                    <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token'] ?>">
                    <?php if (isset($errors)) : ?>
                        <div class="bg-danger text-white text-center">
                            <?php foreach ($errors as $error): ?>
                                <p><?= $error ?></p>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($success)) : ?>
                        <div class="bg-info text-white text-center">
                                <p><?= $success ?></p>
                        </div>
                    <?php endif; ?>

                    <input type="submit" class="btn btn-primary btn-sm" value="Envoyer">
                </form>


            </div>
            <div class="col-md-6 col-md-offset-3 well-bottom">
                <a href="<?= url('admin/manager') ?>" class="pull-right btn btn-primary btn-sm btn-bg-primary"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Retour</a>
            </div>
        </div>
    </div>
</section>
