<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Aide | Paparazza</title>
        <meta name="description" content="page d'aide éditeur paparazza">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <style type="text/css">
            main {
                margin-left: 10px;
                margin-right: 10px;
            }
        </style>
    </head>
    <body>
        <main>
            <h1>Aide pour l'éditeur de texte</h1>

            <section>
                <h2>Zones éditables</h2>
                <ul>
                    <li>Titre avant mosaïque</li>
                    <li>Titre + texte résumés des produits</li>
                    <li>Section produits :
                        <ul>
                            <li>Titres et descriptifs des produits</li>
                            <li>Descriptif des produits en vente</li>
                        </ul>
                    </li>
                    <li>Prestations : contenu des 4 zones prestation</li>
                    <li>Galerie Photo : texte informatif (entre le titre et les photos)</li>
                    <li>Contact : texte informatif</li>
                    <li>Patenaires : titre + texte informatif</li>
                </ul>
                <p>Si vous effacez tout le texte d'une zone éditable, celle-ci n'apparaîtra que lorsque vous activez l'éditeur, signalée par trois points de suspension (...).</p>
            </section>

            <section>
                <h2>Edition</h2>
                <p>Vous ne pouvez éditer que du texte, les options image et vidéo ne fonctionnent pas.</p>
                <p><b>Les modifications apportées sont enregistrées directement sur les fichiers</b>, vos visiteurs les verront dès lors qu'elles sont enregistrées. Vous pouvez annuler une modification tant que vous n'avez pas validé. Si vous avez validé, un système de récupération est disponible via le Tableau de bord > Produits (Backup).</p>

                <h3>Ecrire du texte</h3>
                <p>Après avoir actionné l'éditeur (bouton bleu en haut à gauche), cliquez sur une zone éditable.</p>
                <p>Vous pouvez alors selectionner dans la boite à outils, les <b>titres</b> (H), <b>paragraphes</b> ou <b>listes</b>.</p>
                <p>Vous pouvez éditer le style du texte avec gras, italique, alignement à gauche, centré ou à droite.</p>
                <p>Selon l'élément selectionné d'autres options de mise en page s'offrent à vous en cliquant sur l'élément (flèche dans le bandeau en bas de l'écran). Une fenêtre s'ouvre alors et vous pouvez activer ou déscativer les options.</p>

                <h3>Annuler une modification</h3>
                <p>En cliquant sur la croix rouge, vous annulez toutes les modifications qui n'ont pas été sauvegardées.</p>
                <p>Vous pouvez aussi revenir en arrière avec CTRL+Z ou le bouton <i class="fa fa-undo" aria-hidden="true"></i></p>
                <p>Utilisez le système de backup dans le menu Produits de votre Tableau de bord, afin de garder une version propre de votre site.</p>

                <h3>Enregistrer les modifications</h3>
                <p>Pour valider vos modifications, cliquez sur le bouton vert.</p>
                <p>Il n'y a pas de sauvegarde automatique, pensez à valider votre travail régulièrement.</p>
            </section>

        </main>
    </body>
</html>
