<h1 class="text-center well well-bottom bg-dark">Informations publiques</h1>
<section class="text-center well-bottom">
    <div class="container container-wide bg-white">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <p class="well">Ces informations sont celles qui apparaîssent sur votre site au niveau du formulaire de contact ainsi que dans le pied de page.</p>
                <?php if (isset($errors)) : ?>
                    <p class="bg-danger text-white text-center">Les modifications n'ont pas pu être enregistrées car un ou plusieurs champs sont incomplets ou manquants.</p>
                <?php endif; ?>
                <form id="infosForm" class="text-center" action="<?= url('admin/infos/edit') ?>" method="post">
                    <div class="well">
                        <h3 class="well-bottom">Email</h3>
                        <input type="email" class="form-control" name="email" data-constraints="@NotEmpty @Email" value="<?= $infos->getEmail() ?>">
                        <p class="bg-warning">Attention, modifier cette adresse ne change pas la destination des mails envoyés via le formulaire de contact. </p>
                    </div>
                    <div class="well" id="fieldAdress1">
                        <h3 class="well-bottom">Adresse 1</h3>

                        <label for="adress1">N° et rue</label>
                        <input type="text" class="form-control" name="adress1" data-constraints="@NotEmpty" value="<?= $infos->getAdress1() ?>">

                        <label for="complt_adress1">Complément d'adresse (facultatif)</label>
                        <input type="text" class="form-control" name="complt_adress1"
                            <?php if (is_null($infos->getCompltAdress1())): ?>
                                placeholder="..."
                            <?php else: ?>
                                value="<?= $infos->getCompltAdress1() ?>"
                        <?php endif; ?>>

                        <label for="cp1">Code postal</label>
                        <input type="text" class="form-control" name="cp1" data-constraints="@NotEmpty" value="<?= $infos->getCp1() ?>">

                        <label for="city1">Ville</label>
                        <input type="text" class="form-control" name="city1" data-constraints="@NotEmpty" value="<?= $infos->getCity1() ?>">
                    </div>
                    <?php if (is_null($infos->getAdress2())): ?>
                        <p class="well"><a href="#" data-target="adress2" data-show="true"><i class="fa fa-plus-circle" aria-hidden="true"></i> Ajouter une deuxième adresse</a></p>
                    <?php else: ?>
                        <p class="well" style="display:none;"><a href="#" data-target="adress2" data-show="true"><i class="fa fa-plus-circle" aria-hidden="true"></i> Ajouter une deuxième adresse</a></p>
                        <div class="well" id="fieldAdress2">
                            <h3 class="well-bottom">Adresse 2 (facultatif)</h3>

                            <label for="adress2">N° et rue</label>
                            <input type="text" class="form-control" name="adress2" data-constraints="@NotEmpty" value="<?= $infos->getAdress2() ?>">

                            <label for="complt_adress2">Complément d'adresse (facultatif)</label>
                            <input type="text" class="form-control" name="complt_adress2" value="<?= $infos->getCompltAdress2() ?>">

                            <label for="cp2">Code postal</label>
                            <input type="text" class="form-control" name="cp2" data-constraints="@NotEmpty" value="<?= $infos->getCp2() ?>">

                            <label for="city2">Ville</label>
                            <input type="text" class="form-control" name="city2" data-constraints="@NotEmpty" value="<?= $infos->getCity2() ?>">
                            <p class="well"><a href="#" data-target="adress2"><i class="fa fa-times-circle" aria-hidden="true"></i> Supprimer cette adresse</a></p>
                        </div>
                    <?php endif; ?>
                    <div class="well" id="fieldTel1">
                        <h3 class="well-bottom">Téléphone 1</h3>

                        <label for="tel1">N°</label>
                        <input type="text" class="form-control" name="tel1" data-constraints="@NotEmpty" value="<?= $infos->getTel1() ?>">

                    </div>
                    <?php if (is_null($infos->getTel2())): ?>
                        <p class="well"><a href="#" data-target="tel2" data-show="true"><i class="fa fa-plus-circle" aria-hidden="true"></i> Ajouter un deuxième numéro de téléphone</a></p>

                    <?php else: ?>
                        <p class="well" style="display:none;"><a href="#" data-target="tel2" data-show="true"><i class="fa fa-plus-circle" aria-hidden="true"></i> Ajouter un deuxième numéro de téléphone</a></p>
                        <div class="well" id="fieldTel2">
                            <h3 class="well-bottom">Téléphone 2 (facultatif)</h3>

                            <label for="tel2">N°</label>
                            <input type="text" class="form-control" name="tel2" data-constraints="@NotEmpty" value="<?= $infos->getTel2() ?>">
                            <p class="well"><a href="#" data-target="tel2"><i class="fa fa-times-circle" aria-hidden="true"></i> Supprimer ce numéro de téléphone</a></p>

                        </div>
                    <?php endif; ?>
                    <div class="well-bottom">
                        <?php if (isset($errors)) : ?>
                            <div class="bg-danger text-white text-center">
                                <?php foreach ($errors as $error): ?>
                                    <p><?= $error ?></p>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                        <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token'] ?>">
                        <input type="submit" class="btn btn-primary btn-large" value="Enregistrer les modifications">
                    </div>
                </form>
            </div>

            <div class="col-md-6 col-md-offset-3 well-bottom">
                <a href="<?= url('admin/dashboard') ?>" class="pull-right btn btn-primary btn-sm btn-bg-primary"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Retour</a>
            </div>
        </div>
    </div>
</section>
