<h1 class="text-center well bg-dark">Gestion du Slider</h1>
<section class="text-center">
    <div class="container container-wide bg-white">
        <?php if(isset($slides)): ?>
          <div class="row">
              <div class="col-md-6 col-md-offset-3 well well-bottom">
                  <h3>Supprimer une/des image(s)</h3>
                  <hr>
                    <form action="<?= url('admin/slider/destroy') ?>" method="post">
                      <?php foreach ($slides as $slide):?>
                        <label for="<?= $slide->getImgSrc() ?>">
                          <div data-lightbox="gallery" class="flow-offset-1">
                              <div class="col-xs-6 col-md-3">
                                <img src="<?= url('uploads/slider/' . $slide->getImgSrc()) ?>" alt="Image 1"/>
                                <input type="checkbox" id="<?= $slide->getImgSrc() ?>" name="slidesToDelete[]" value="<?= $slide->getId(); ?>">
                              </div>
                          </div>
                        </label>
                      <?php endforeach; ?>
                      <div class="row">
                        <div class="col-md-12 inset-2">
                          <button type="submit" class="btn btn-primary">Supprimer</button>
                        </div>
                      </div>
                  </form>
              </div>
          </div>
        <?php endif; ?>
        <div class="row">
          <div class="col-md-6 col-md-offset-3 well-bottom">
            <?php if (isset($errors) && !empty($errors)) : ?>
                <div class="bg-danger text-white">
                    <?php foreach ($errors as $error): ?>
                        <p><?= $error ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if (isset($_GET['success']) && $_GET['success']) : ?>
                <div class="bg-info text-white">
                        <?= 'Le slider a bien été mis à jour'; ?>
                </div>
            <?php endif; ?>
          </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 well well-bottom">
                <h3>Ajouter une nouvelle image</h3>
                <hr>
                <form  method="post" enctype="multipart/form-data" action="<?= url('admin/slider/create') ?>">

                  <div class="row">
                    <div class="col-md-12">
                      <label for="uploaded_img">Importer une image (taille maximum : 10Mo)</label>
                      <input type="file" name="uploaded_img"  class="form-control"/>
                      <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12 inset-2">
                      <label for="description">Description de l'image (facultatif)</label>
                      <input type="text" name="description" placeholder="description..." class="form-control">
                    </div>
                  </div>

                  <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token'] ?>">
                  <button type="submit" class="btn btn-primary">Ajouter</button>

                </form>
            </div>
          </div>


            <div class="col-md-6 col-md-offset-3 well-bottom">
                <a href="<?= url('admin/dashboard') ?>" class="pull-right btn btn-primary btn-sm btn-bg-primary"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Retour</a>
            </div>



    </div>
</section>
