<h1 class="text-center well well-bottom bg-dark">Gestion des administateurs</h1>
<section class="text-center well">
    <div class="container container-wide bg-white">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 well well-bottom">
                <h3>Supprimer une/des image(s)</h3>
                <?php foreach ($slides as $slide):?>
                  <div data-lightbox="gallery" class="flow-offset-1">
                      <div class="col-xs-6 col-md-3">
                              <img src="<?= url('uploads/slider/' . $slide->getImgSrc()) ?>" alt="Image 1"/>
                      </div>
                  </div>
                <?php endforeach; ?>
                <a href="<?= url('admin/slider/delete') ?>" class="btn btn-primary">Supprimer</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 well well-bottom">
                <h3>Ajouter une nouvelle image</h3>
                <form  method="post" enctype="multipart/form-data" action="<?= url('admin/slider/create') ?>">

                  <label for="uploaded_img">Importer une image (taille maximum : 10Mo)</label>
                  <input type="file" name="uploaded_img"  class="form-control"/>
                  <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />

                  <label for="description">Description de l'image (facultatif)</label>
                  <input type="text" name="description" placeholder="description..." class="form-control">

                  <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token'] ?>">
                  <button type="submit" name="button" class="btn btn-primary">Ajouter</button>

                </form>
            </div>
              <?php if (isset($errors) && !empty($errors)) : ?>
                  <div class="bg-danger text-white">
                      <?php foreach ($errors as $error): ?>
                          <p><?= $error ?></p>
                      <?php endforeach; ?>
                  </div>
              <?php endif; ?>

              <?php if (isset($success)) : ?>
                  <div class="bg-info text-white">
                          <p><?= $success ?></p>
                  </div>
              <?php endif; ?>
            </div>

            <div class="col-md-6 col-md-offset-3 well-bottom">
                <a href="<?= url('admin/dashboard') ?>" class="pull-right btn btn-primary btn-sm btn-bg-primary"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Retour</a>
            </div>



    </div>
</section>
